spring.application.name=team4you

spring.docker.compose.lifecycle-management=start_only

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.bucket-name=${AWS_BUCKET_NAME}
aws.endpoint-url=${AWS_ENDPOINT_URL}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.webauthn=TRACE
logging.level.backendlab.team4you.config=DEBUG
