spring.application.name=team4you

spring.docker.compose.lifecycle-management=start_only

spring.datasource.url=jdbc:postgresql://localhost:5432/team4you
spring.datasource.username=team4you
spring.datasource.password=team4you

spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true