CREATE TABLE application_entity (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             name VARCHAR(255) NOT NULL,
                             email VARCHAR(255) NOT NULL,
                             phone VARCHAR(50),
                             message TEXT,
                             created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);