
CREATE TABLE log_entry
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action VARCHAR(255) NOT NULL,
    performed_by VARCHAR(255) NOT NULL,
    details TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT current_timestamp,

    CONSTRAINT pk_log_entry PRIMARY KEY (id)
);