CREATE TABLE case_file (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           case_record_id BIGINT NOT NULL,
                           original_file_name VARCHAR(255) NOT NULL,
                           s3_key VARCHAR(1024) NOT NULL,
                           content_type VARCHAR(255) NOT NULL,
                           size_in_bytes BIGINT NOT NULL,
                           uploaded_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

                           CONSTRAINT pk_case_file PRIMARY KEY (id),

                           CONSTRAINT uk_case_file_s3_key UNIQUE (s3_key),

                           CONSTRAINT fk_case_file_case_record
                               FOREIGN KEY (case_record_id)
                                   REFERENCES case_record (id)
                                   ON DELETE CASCADE
);
