ALTER TABLE log_entry
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;


ALTER TABLE booking
    ALTER COLUMN booking_time TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE booking
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE case_record
    ALTER COLUMN opened_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE case_record
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE case_record
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE case_record
    ALTER COLUMN closed_at TYPE TIMESTAMP WITH TIME ZONE;