CREATE TABLE audit (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       username VARCHAR(255),
                       email VARCHAR(255),
                       details VARCHAR(255),
                       action VARCHAR(255),
                       endpoint VARCHAR(255),
                       http_method VARCHAR(255),
                       ip_address VARCHAR(255),
                       timestamp TIMESTAMP,
                       status VARCHAR(255)
);