create table protocol (
                          id bigint generated by default as identity primary key,
                          meeting_id bigint not null,
                          registry_id bigint not null,
                          title varchar(255) not null,
                          protocol_year integer not null,
                          created_at timestamp not null,

                          constraint uk_protocol_meeting unique (meeting_id),

                          constraint fk_protocol_meeting
                              foreign key (meeting_id) references meeting(id),

                          constraint fk_protocol_registry
                              foreign key (registry_id) references registry(id)
);

create table protocol_paragraph (
                                    id bigint generated by default as identity primary key,
                                    protocol_id bigint not null,
                                    case_record_id bigint not null,
                                    paragraph_number bigint not null,
                                    heading varchar(255) not null,

                                    constraint fk_protocol_paragraph_protocol
                                        foreign key (protocol_id) references protocol(id),

                                    constraint fk_protocol_paragraph_case_record
                                        foreign key (case_record_id) references case_record(id)
);

create table protocol_paragraph_sequence (
                                             id bigint generated by default as identity primary key,
                                             registry_id bigint not null,
                                             sequence_year integer not null,
                                             last_value bigint not null,

                                             constraint uk_protocol_paragraph_sequence_registry_year
                                                 unique (registry_id, sequence_year),

                                             constraint fk_protocol_paragraph_sequence_registry
                                                 foreign key (registry_id) references registry(id)
);