CREATE TABLE registry
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(100)                            NOT NULL,
    code       VARCHAR(2)                              NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
    CONSTRAINT pk_registry PRIMARY KEY (id)
);

ALTER TABLE registry
    ADD CONSTRAINT uc_registry_code UNIQUE (code);

ALTER TABLE registry
    ADD CONSTRAINT uc_registry_name UNIQUE (name);

ALTER TABLE registry
    ADD CONSTRAINT chk_registry_code_format
        CHECK (code ~ '^[A-Z]{2}$');