CREATE TABLE contact_messages (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  first_name VARCHAR(255),
                                  last_name VARCHAR(255),
                                  email VARCHAR(255),
                                  phone VARCHAR(50),
                                  message TEXT,
                                  submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);