CREATE TABLE case_number_sequence
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    registry_id   BIGINT                                  NOT NULL,
    sequence_year INTEGER                                 NOT NULL,
    last_value    BIGINT                                  NOT NULL,
    CONSTRAINT pk_case_number_sequence PRIMARY KEY (id)
);

ALTER TABLE case_number_sequence
    ADD CONSTRAINT uk_case_number_sequence_registry_year UNIQUE (registry_id, sequence_year);

ALTER TABLE case_number_sequence
    ADD CONSTRAINT fk_case_number_sequence_registry FOREIGN KEY (registry_id) REFERENCES registry (id);