CREATE TABLE case_record
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    case_number           VARCHAR(50)                             NOT NULL,
    registry_id           BIGINT                                  NOT NULL,
    title                 VARCHAR(255)                            NOT NULL,
    description           TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'OPEN',
    owner_user_id         VARCHAR(255)                            NOT NULL,
    assigned_user_id      VARCHAR(255)                            NOT NULL,
    confidentiality_level VARCHAR(50) NOT NULL DEFAULT 'OPEN',
    opened_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT current_timestamp,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    closed_at             TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_case_record PRIMARY KEY (id)
);

ALTER TABLE case_record
    ADD CONSTRAINT uk_case_record_case_number UNIQUE (case_number);

ALTER TABLE case_record
    ADD CONSTRAINT FK_CASE_RECORD_ON_ASSIGNED_USER FOREIGN KEY (assigned_user_id) REFERENCES app_user (id);

ALTER TABLE case_record
    ADD CONSTRAINT FK_CASE_RECORD_ON_OWNER_USER FOREIGN KEY (owner_user_id) REFERENCES app_user (id);

ALTER TABLE case_record
    ADD CONSTRAINT FK_CASE_RECORD_ON_REGISTRY FOREIGN KEY (registry_id) REFERENCES registry (id);