CREATE TABLE case_record
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    case_number           VARCHAR(50)                             NOT NULL,
    registry_id           BIGINT                                  NOT NULL,
    title                 VARCHAR(255)                            NOT NULL,
    description           TEXT,
    status                VARCHAR(50) NOT NULL DEFAULT 'OPEN',

    owner_user_id         BIGINT                                  NOT NULL,
    assigned_user_id      BIGINT                                  NOT NULL,

    confidentiality_level VARCHAR(50) NOT NULL DEFAULT 'OPEN',
    opened_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT current_timestamp,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    closed_at             TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_case_record PRIMARY KEY (id)
);

ALTER TABLE case_record
    ADD CONSTRAINT fk_case_record_on_assigned_user
        FOREIGN KEY (assigned_user_id) REFERENCES user_entities (id);

ALTER TABLE case_record
    ADD CONSTRAINT fk_case_record_on_owner_user
        FOREIGN KEY (owner_user_id) REFERENCES user_entities (id);

ALTER TABLE case_record
    ADD CONSTRAINT fk_case_record_on_registry
        FOREIGN KEY (registry_id) REFERENCES registry (id);